
service:

  django:
    container_name: hms_core
    build:
      context: ./core
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./core:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=
      - ALLOWED_HOSTS=localhost,127.0.0.1
