# Generated by Django 5.1 on 2024-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
