# Generated by Django 5.1.1 on 2024-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage Grade'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cmp_video',
            field=models.FileField(blank=True, null=True, upload_to='compressed_videos/', verbose_name='cmp_video'),
        ),
    ]
