# Generated by Django 5.1.2 on 2024-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
