# Generated by Django 5.1.1 on 2024-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_hls_path_alter_submission_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid360p',
            field=models.FileField(blank=True, null=True, upload_to='compressed_videos/link_hls/', verbose_name='hls_video'),
        ),
    ]
