# Generated by Django 5.1.1 on 2024-10-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedbackmessage_grade'),
        ('api', '0002_video_assignment'),
    ]

    operations = [
    ]
