# Generated by Django 5.1.1 on 2024-10-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_status_assignment_total_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_length',
        ),
    ]
