# Generated by Django 5.1.1 on 2024-10-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_status_assignment_total_submissions'),
        ('api', '0003_merge_20241013_0034'),
    ]

    operations = [
    ]
