# Generated by Django 5.1.2 on 2024-10-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_status_assignment_total_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='lecturer',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='feedback',
        ),
    ]
