# Generated by Django 5.1.1 on 2024-09-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
    ]
