# Generated by Django 5.1.2 on 2024-10-16 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_lecturer_grade_student_remove_grade_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Grade'),
        ),
    ]
