# Generated by Django 5.1.2 on 2024-10-16 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_grade_letter_grade_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Grade'),
        ),
        migrations.AddField(
            model_name='submission',
            name='letter_grade',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
