# Generated by Django 5.1.2 on 2024-10-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_grade_submission_letter_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_length',
        ),
    ]
