# Generated by Django 5.1.2 on 2024-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
