# Generated by Django 5.1.1 on 2024-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20241015_1838'),
        ('api', '0009_submission_marked'),
    ]

    operations = [
    ]
