# Generated by Django 5.1.1 on 2024-10-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_0004_merge_20241015_1838_0009_submission_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
