name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Deploy to production (optional)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy@v1
        with:
          name: Deploy Django app
          path: .
          strategy: basic
          run: python manage.py migrate && python manage.py collectstatic
